alter table folio_objects change folio_object_number folio_object_number varchar(255) NOT NULL;
alter table folio_objects change active active boolean DEFAULT 0;
alter table folio_objects change created_date created_date timestamp DEFAULT CURRENT_TIMESTAMP;

insert into folio_objects (id, folio_object_number, last_update) values(1, 'FOLIO 00001', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(2, 'FOLIO 00002', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(3, 'FOLIO 00003', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(4, 'FOLIO 00004', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(5, 'FOLIO 00005', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(6, 'FOLIO 00006', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(7, 'FOLIO 00007', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(8, 'FOLIO 00008', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(9, 'FOLIO 00009', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(10, 'FOLIO 00010', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(11, 'FOLIO 00011', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(12, 'FOLIO 00012', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(13, 'FOLIO 00013', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(14, 'FOLIO 00014', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(15, 'FOLIO 00015', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(16, 'FOLIO 00016', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(17, 'FOLIO 00017', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(18, 'FOLIO 00018', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(19, 'FOLIO 00019', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(20, 'FOLIO 00020', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(21, 'FOLIO 00021', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(22, 'FOLIO 00022', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(23, 'FOLIO 00023', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(24, 'FOLIO 00024', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(25, 'FOLIO 00025', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(26, 'FOLIO 00026', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(27, 'FOLIO 00027', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(28, 'FOLIO 00028', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(29, 'FOLIO 00029', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(30, 'FOLIO 00030', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(31, 'FOLIO 00031', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(32, 'FOLIO 00032', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(33, 'FOLIO 00033', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(34, 'FOLIO 00034', CURRENT_TIMESTAMP);
insert into folio_objects (id, folio_object_number, last_update) values(35, 'FOLIO 00035', CURRENT_TIMESTAMP);