CREATE TABLE `manuscript_images` (
  `id` int(11) NOT NULL DEFAULT '0',
  `manuscript_text_id` int(11) DEFAULT NULL,
  `link_id` int(11) DEFAULT NULL,
  `folio_number` varchar(50) DEFAULT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `notes_to_photographer` varchar(100) DEFAULT NULL,
  `icon_class` varchar(100) DEFAULT NULL,
  `revisit` tinyint(1) DEFAULT NULL,
  `seq` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `manuscript_parts` (
  `id` int(11) NOT NULL DEFAULT '0',
  `manuscript_id` int(11) DEFAULT NULL,
  `part_number` varchar(10) DEFAULT NULL,
  `folio` varchar(120) DEFAULT NULL,
  `outer_dimensions` varchar(100) DEFAULT NULL,
  `country` varchar(40) DEFAULT NULL,
  `cardinal` varchar(40) DEFAULT NULL,
  `region` varchar(50) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `document` tinyint(1) DEFAULT NULL,
  `dated` tinyint(1) DEFAULT NULL,
  `date` varchar(100) DEFAULT NULL,
  `year_month_day` varchar(100) DEFAULT NULL,
  `layout` text,
  `script` text,
  `number_scribes` varchar(255) DEFAULT NULL,
  `scribe` text,
  `music` varchar(255) DEFAULT NULL,
  `support` varchar(50) DEFAULT NULL,
  `water_mark` varchar(255) DEFAULT NULL,
  `representational_decoration` text,
  `other_decoration` text,
  `artist` varchar(150) DEFAULT NULL,
  `notes` text,
  `revisit` tinyint(1) DEFAULT NULL,
  `begin_date` int(11) DEFAULT NULL,
  `end_date` int(11) DEFAULT NULL,
  `seq` int(11) DEFAULT NULL,
  `acknowledgments` varchar(50) DEFAULT NULL,
  `alphabet` varchar(100) DEFAULT NULL,
  `native_date` text,
  `reviser` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `manuscript_texts` (
  `id` int(11) NOT NULL DEFAULT '0',
  `manuscript_part_id` int(11) DEFAULT NULL,
  `folio` varchar(120) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `author_ns` varchar(255) DEFAULT NULL,
  `other_associated_name` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `supplied_title` varchar(255) DEFAULT NULL,
  `supplied_title_ns` varchar(255) DEFAULT NULL,
  `docket` varchar(255) DEFAULT NULL,
  `status_of_text` varchar(255) DEFAULT NULL,
  `rubric` varchar(255) DEFAULT NULL,
  `incipit` varchar(255) DEFAULT NULL,
  `incipit_ns` varchar(255) DEFAULT NULL,
  `explicit` varchar(255) DEFAULT NULL,
  `explicit_ns` varchar(255) DEFAULT NULL,
  `language` varchar(100) DEFAULT NULL,
  `notes_to_text` text,
  `revisit` tinyint(1) DEFAULT NULL,
  `seq` int(11) DEFAULT NULL,
  `acknowledgments` varchar(255) DEFAULT NULL,
  `music` varchar(150) DEFAULT NULL,
  `subject` varchar(150) DEFAULT NULL,
  `reviser` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `manuscripts` (
  `id` int(11) NOT NULL DEFAULT '0',
  `city` varchar(50) DEFAULT NULL,
  `institution` varchar(50) DEFAULT NULL,
  `library` varchar(100) DEFAULT NULL,
  `shelf_mark` varchar(150) DEFAULT NULL,
  `nick_name` varchar(100) DEFAULT NULL,
  `composite` tinyint(1) DEFAULT NULL,
  `folio` varchar(150) DEFAULT NULL,
  `physical_issues` varchar(255) DEFAULT NULL,
  `binding` text,
  `provenance` text,
  `bibliography` text,
  `notes` text,
  `source` varchar(120) DEFAULT NULL,
  `inputter_date` varchar(120) DEFAULT NULL,
  `reviser_date` varchar(120) DEFAULT NULL,
  `revisit` tinyint(1) DEFAULT NULL,
  `reproduction` text,
  `acknowledgments` varchar(150) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `url2` varchar(255) DEFAULT NULL,
  `url3` varchar(255) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `archival_series` varchar(120) DEFAULT NULL,
  `colophon` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;